CREATE TABLE CLIENTES 
( 
    CPF VARCHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,     
    UF VARCHAR(2) NOT NULL,
    CELULAR VARCHAR(11) NOT NULL
); 

CREATE TABLE FINANCIAMENTOS 
( 
    ID uniqueidentifier NOT NULL PRIMARY KEY, 
    CPF VARCHAR(11) NOT NULL,
    TP_FINANCIAMENTO INT NOT NULL,
    VL_TOTAL DECIMAL(9,2) NOT NULL,
    DT_ULTIMO_VENCIMENTO DATE NOT NULL
  
    CONSTRAINT FK_CLIENTES_FINANCIAMENTOS FOREIGN KEY (CPF)
    REFERENCES CLIENTES(CPF)
);

CREATE TABLE PARCELAS 
( 
    ID uniqueidentifier NOT NULL PRIMARY KEY, 
    ID_FINANCIAMENTO uniqueidentifier NOT NULL,
    NR_PARCELA INT NOT NULL,
    VL_PARCELA DECIMAL(9,2) NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    DT_PAGAMENTO DATE

    CONSTRAINT FK_FINANCIAMENTOS_PARCELAS FOREIGN KEY (ID_FINANCIAMENTO)
    REFERENCES FINANCIAMENTOS(ID)
);
